"""Initial migration

Revision ID: cfe91efaa960
Revises: 2b9cc752428f
Create Date: 2025-08-06 22:21:24.868582

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cfe91efaa960'
down_revision: Union[str, Sequence[str], None] = '2b9cc752428f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shareholders', sa.Column('email', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'shareholders', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'shareholders', type_='unique')
    op.drop_column('shareholders', 'email')
    # ### end Alembic commands ###
